name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - '*.x'
  schedule:
    - cron: '0 0 * * 0' # Once in a week run tests to check assertions against updated(if any) ably-js package.

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: ESLint
        run: npm run lint

      - name: Execute tests
        run: npm test

      - name: Run build
        run: npm run build
